import React from 'react';

const TermsOfUse = () => {
  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', padding: 20,fontFamily: 'Montserrat, sans-serif', lineHeight: 1.6 }}>
      <h1>Terms of Use</h1>
      <p>Last updated: August 14, 2025</p>
     <p>Welcome to Store1920! These Terms of Use (“Terms”) are a legally binding agreement between you and Althakeel General Trading LLC, the company that owns and operates the Store1920 platform. Throughout these Terms, “Store1920,” “we,” “us,” or “our” refer to Althakeel General Trading LLC and its affiliates. “You” refers to you as a user of our website, mobile applications, and any related services (collectively, the “Services”). By registering for an account or by accessing or using our Services, you agree to these Terms. If you do not agree with these Terms, you must not use our Services.</p>
     <p>Please read these Terms carefully before using Store1920. They contain important information about your rights and obligations, as well as limitations and exclusions that may apply to you.</p>
      
      
      <h2>1. Overview</h2>
<p><strong>1.1 Contracting Entity.</strong> These Terms are between you and Althakeel General Trading LLC, a company registered in the United Arab Emirates. Althakeel General Trading LLC (and its current or future affiliates) is referred to in these Terms as “we” or “us.” This means when you make a purchase or interact with Store1920, you are entering into a contract with Althakeel General Trading LLC.</p>
<p><strong>1.2 Services Definition.</strong> Store1920 operates an e-commerce marketplace through its website (store1920.com) and mobile application. In these Terms, our website, app, and related services—including features that facilitate the buying and selling of goods—are collectively referred to as the “Services.” Any new features or tools added to the current Services will also be subject to these Terms.</p>

<p><strong>1.3 Users.</strong> Store1920 provides a platform for buyers to purchase a variety of products from sellers (also called “merchandise partners”). In these Terms, all individuals or entities using the Services—whether as buyers, visitors, or sellers—are referred to as “users.” If you are using the Services on behalf of a company or another legal entity, you represent that you have the authority to bind that entity to these Terms. In such cases, “you” refers to both you (the individual) and the entity you represent.</p>

<p><strong>1.4 Additional Policies.</strong> Your use of the Services is also governed by other policies that we publish and update periodically. These include, but are not limited to, our Privacy Policy, Cookie Policy, Return & Refund Policy, Purchase Protection Program, and Intellectual Property Policy. These policies are incorporated by reference into these Terms. In the event of a conflict between these Terms and any Policy with respect to a specific subject matter, the Policy will control. We encourage you to read all applicable policies carefully to understand the rules and expectations for using our Services.</p>
<p><strong>1.5 Changes to Terms.</strong> We reserve the right to modify or update these Terms at any time at our sole discretion, in accordance with applicable laws. When changes are made, we will post the updated Terms on our website and update the “Last updated” date at the top. For significant changes, we may also provide a notice to you (for example, via email or a notification on our site). Any modifications will only take effect after we notify you and give you an opportunity to review them. If you continue to use the Services after the updated Terms take effect, you will be deemed to have accepted the revised Terms. If you do not agree to a change, you must stop using the Services and may close your account. (Note: Material changes will not retroactively affect actions already taken under a previous version of the Terms.)</p>




      <h2>2. User Requirements and Account Registration</h2>
     <p><strong>2.1 Eligibility – Adults Only, Personal Use Only.</strong> The Services are intended solely for users who are at least 18 years old and legally able to enter into a binding contract in your jurisdiction. By using our Services, you represent that you meet these eligibility requirements. If you are under 18, you must not create an account or use Store1920. While some products on Store1920 may be for children, they are only available for purchase by adults. You also agree to use the Services solely for personal, non-commercial purposes. (Separate terms apply if you become a seller or partner on our platform; unless you have entered such an agreement with us, you may not use the Services for commercial resale.)</p>

<p><strong>2.2 Prohibited Users.</strong> You may not use the Services if: (a) you are under the required age as stated above; (b) you have been suspended or removed from our platform by us; or (c) using the Services is prohibited by laws applicable to you (for example, if you are in a country or region subject to U.A.E. sanctions or other trade restrictions). It is your responsibility to ensure that your use of the Services complies with all applicable laws, rules, and regulations. By using the Services, you confirm that doing so does not violate any such laws.</p>

<p><strong>2.3 Account Registration.</strong> While you can browse store1920.com without registering, certain features—such as making purchases or tracking orders—require an account. When creating an account, you must provide truthful, accurate, and complete information, and keep it up to date. This includes a valid email address and any other information requested during signup. You are responsible for safeguarding your login credentials, and you must notify us immediately of any unauthorized use of your account. Store1920 is not liable for any loss or damage resulting from someone else using your account due to your failure to keep your login details confidential. You may not create multiple accounts to bypass restrictions or violate these Terms. Accounts cannot be transferred without our prior written consent.</p>

<p><strong>2.4 Account Integrity.</strong> We reserve the right to refuse registration or cancel accounts at our discretion, such as when information provided is false or if we previously terminated an account for violating our Terms. You are responsible for all activity on your account, so use strong passwords and avoid reusing credentials from other sites. We assume that any communications from your account or associated email address come from you.</p>

<p><strong>2.5 Social Media Login.</strong> Store1920 may allow registration or login via third-party services (e.g., Google, Facebook, Apple). If you choose to use a social networking service (SNS) account, we may receive certain profile information from that SNS, as permitted by your agreement with the SNS and your privacy settings. You are responsible for maintaining the confidentiality of your SNS account login and for any activity performed under that account.</p>


      <h2>3. Use of the Services</h2>
<p><strong>3.1 Allowed Use.</strong> We grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Store1920 Services for the purpose of shopping for personal items, in accordance with these Terms. All rights not expressly granted to you are reserved by Store1920.</p>

<p><strong>3.2 Prohibited Activities.</strong> You agree not to misuse our Services. This includes not doing (or attempting to do) any of the following:  
<ul>
  <li>Violating any laws or regulations in connection with your access to or use of the Services.</li>
  <li>Engaging in any fraudulent or deceptive practices.</li>
  <li>Disrupting or interfering with the normal operation of the Services or the experience of other users, such as by distributing viruses, malware, or any other harmful code.</li>
  <li>Data mining, scraping, crawling, or using any robot, spider, or other automated means to access the Services for any purpose without our express written permission. (This does not prohibit public search engines from indexing pages as permitted by our robots.txt file.)</li>
  <li>Attempting to probe, scan, or test the vulnerability of our systems or networks, or breaching any security or authentication measures.</li>
  <li>Copying, reproducing, distributing, publicly performing, or publicly displaying any content from the Services (other than content you have submitted) without our prior written consent, except as allowed by fair use or other applicable law.</li>
  <li>Using the Services to send unsolicited advertising or spam.</li>
  <li>Impersonating any person or entity, or falsely stating or otherwise misrepresenting your affiliation with a person or entity.</li>
  <li>Reverse engineering or decompiling any part of the Services, or doing anything that might discover source code or bypass measures we have put in place to prevent or restrict access to any portion of the Services.</li>
  <li>Collecting information about other users without their consent.</li>
  <li>Posting or transmitting any content that is illegal, infringing, defamatory, harassing, obscene, or otherwise objectionable (including content that violates our Intellectual Property Policy or any third party’s rights).</li>
</ul>
We reserve the right to take appropriate action if you engage in any of the above, including terminating or suspending your account and access to the Services, and cooperating with law enforcement where applicable.</p>

<p><strong>3.3 User Content.</strong> When you post content on Store1920 (for example, product reviews, comments, images, or other materials, collectively “User Content”), you retain ownership of your content. However, you hereby grant Store1920 a worldwide, royalty-free, perpetual, irrevocable, non-exclusive, sublicensable license to use, reproduce, modify, adapt, publish, translate, distribute, and display your User Content in any media or distribution methods (now known or later developed) as necessary to operate and promote the Services (for example, displaying your review on the product page). You represent that you have all necessary rights to the User Content you submit and that sharing your content does not violate the rights of any third party. We have the right (but no obligation) to remove or edit User Content for any reason, including if we believe it violates these Terms or our policies.</p>
<p><strong>3.4 Privacy of Others.</strong> If you receive information about another Store1920 user (for example, a seller receiving a buyer’s shipping address), you must keep that information confidential and use it only for the Store1920 transaction or other Services-related communications that are not unsolicited commercial messages, unless you have the consent of the other user. You may not use another user’s personal data for marketing purposes without their explicit permission.</p>

<p><strong>3.5 Third-Party Links and Services.</strong> Our Services may contain links to third-party websites or services that we do not own or control (for example, a manufacturer’s site or integrations with social media). Some features of our Services may also require using a third-party product or service (such as an updated browser or mobile device). When you access these third-party services, you do so at your own risk. These third parties may have their own terms and policies, and we are not responsible for their content or practices. Store1920 does not endorse any third-party sites or services linked from our platform.</p>

<p><strong>3.6 Changes to Services.</strong> Store1920 is constantly evolving and improving. We may add, modify, or remove functionalities or features of the Services at any time (for example, discontinuing a feature that is not widely used or changing the look and feel of our app). We also reserve the right to suspend or discontinue the Services altogether. If such changes significantly affect your usage, we will provide reasonable advance notice to retrieve your account information or content.</p>






      <h2>4. Purchases and Payments</h2>
<p><strong>4.1 Ordering and Acceptance.</strong> When you place an order on Store1920, you are committing to purchase the products in that order at the price indicated, subject to these Terms. After placing an order, we (or the product’s seller) will send an order confirmation to the email address associated with your account. This confirmation acknowledges receipt of your order request; however, the contract of sale is only formed when we dispatch the product to you. We reserve the right to cancel or refuse any order before dispatch for reasons such as suspected fraud, unauthorized or illegal transactions, product availability, pricing errors, or other issues identified by our order processing team. If your order is cancelled and payment has already been processed, we will issue a refund.</p>

<p><strong>4.2 Product Information.</strong> We strive to ensure that product descriptions, images, pricing, and other details on Store1920 are accurate and up-to-date. However, errors can occur. If a product is not as described when you receive it, your sole remedy is to return it in unused condition for a refund in accordance with our Return & Refund Policy. Minor differences in color or appearance due to screen differences may occur and alone do not qualify as “not as described” if the product is otherwise correct.</p>

<p><strong>4.3 Pricing and Availability.</strong> All prices are shown in the currency applicable to your region (e.g., AED for the U.A.E.) unless stated otherwise. Prices and product availability can change at any time without notice. Promotions or sales may have specific terms. Occasionally, some products may be mispriced. If the correct price is higher than stated, we may contact you for instructions before shipping or cancel your order and notify you. If a product is temporarily out of stock, we will try to indicate this on the product page or prevent checkout. In rare cases, two customers may order the last item simultaneously; in such cases, we fulfill orders in the sequence received until stock is depleted.</p>

<p><strong>4.4 Payments.</strong> Store1920 offers various payment methods (e.g., credit/debit card, PayPal, or possibly Cash on Delivery). By submitting an order, you authorize us (or our designated payment processor) to charge the full order amount to your selected payment method. You represent that you are authorized to use the payment method and that the payment information provided is accurate. In the event of a payment failure or dispute, we may cancel the order. All payment transactions are handled by third-party processors, which may have their own terms. Store1920 does not store full payment card details; these are securely handled by the payment processor.</p>

<p><strong>4.5 Taxes and Duties.</strong> Prices on Store1920 may or may not include applicable taxes, duties, or fees. Depending on your shipping destination, you may be responsible for payment of taxes (such as VAT) or import duties. At checkout, we will typically indicate whether taxes are included or if duties may apply upon delivery. If not fully clarified, you acknowledge that you are responsible for any such taxes or duties related to your purchases. For international shipments, customs policies vary, and you may need to pay import duties once the shipment reaches your country. Store1920 has no control over these charges and cannot always predict their amount.</p>
<p><strong>4.6 Shipping.</strong> We will arrange for the shipment of products to you. Please review our Shipping Information policy for details on shipping methods, costs, and delivery timeframes. Shipping times are estimates and are not guaranteed, as delays can occur beyond our control (for example, customs holds or carrier issues). Title and risk of loss for products you purchase pass to you upon delivery to the carrier, except where applicable law provides otherwise. Any loss or damage during shipping is the responsibility of the carrier, but we will assist customers in working with the carrier or pursuing any insurance claims as appropriate.</p>

<p><strong>4.7 Late Deliveries.</strong> We aim to meet the delivery estimates provided, and we understand it can be frustrating if a package is late. If your order is significantly delayed beyond the estimated window, please contact Customer Service. In some cases, as part of our customer service commitment, Store1920 may offer a small courtesy credit for late deliveries or allow you to cancel the order for a full refund if the item has not yet shipped and is excessively delayed. Refer to our Shipping Info page for any on-time delivery guarantee or credit policy (if applicable). Any such credits are discretionary and subject to terms.</p>

<p><strong>4.8 Returns and Refunds.</strong> If you are not satisfied with a product you purchased, you may be eligible to return it and receive a refund under our Return & Refund Policy. This policy (available on our site) outlines which items are returnable, the time frame for returns (generally 90 days from purchase for most items), the condition items must be in, and how refunds are issued. To initiate a return, follow the instructions in the policy or on the Store1920 platform (e.g., via your order history). Most items can be returned within 90 days if they are in new, unused condition with original packaging, except certain excluded categories (such as perishable goods or intimate apparel that has been worn). The first return for any order ships back free; subsequent returns from the same order may incur a return shipping fee. Refunds are typically issued to your original payment method or as Store1920 credits, depending on your choice (Store1920 credits are often processed faster). For full details, please read the Return & Refund Policy. Store1920 stands by its products and will work to ensure your satisfaction consistent with that policy.</p>

<p><strong>4.9 Purchase Protection.</strong> All purchases on Store1920 are covered by our Purchase Protection Program (see separate policy). This program provides remedies if an order never arrives, arrives damaged, or does not match the description. In qualifying cases, you can receive a full refund under the program. We encourage you to familiarize yourself with this program, which is designed to give you peace of mind while shopping on Store1920.</p>

<p><strong>4.10 Errors and Inaccuracies.</strong> Occasionally, information on our site or in the Services may contain typographical errors, inaccuracies, or omissions relating to product descriptions, pricing, promotions, or availability. Store1920 reserves the right to correct any errors, inaccuracies, or omissions and to change or update information or cancel orders if any information in the Services or on any related website is inaccurate at any time without prior notice (including after you have submitted your order). If this affects your order, we will notify you. We apologize for any inconvenience this may cause.</p>









      <h2>5. Intellectual Property and Content</h2>
<p><strong>5.1 Store1920 Content.</strong> All content available on the Services (except for User Content, defined above) – including but not limited to text, graphics, logos, button icons, images, audio clips, software, and data compilations – is the property of Store1920 or our content suppliers and is protected by intellectual property laws. The compilation of all content on our platform is our exclusive property. Store1920 and its suppliers retain all rights, title, and interest in and to the Services and content provided through the Services, including all related intellectual property rights. You agree not to copy, distribute, modify, or create derivative works from any portion of the Services without our express permission, except as allowed by law or as enabled by a feature of the Services.</p>

<p><strong>5.2 Trademarks.</strong> “Store1920,” our logos, and any other product or service name or slogan displayed on our Services are trademarks of Althakeel General Trading LLC or our affiliates/suppliers, and may not be copied, imitated, or used (in whole or in part) without our prior written permission. All other trademarks, registered trademarks, product names, and company names or logos mentioned on the Services are the property of their respective owners and may not be used without permission from the respective owner.</p>

<p><strong>5.3 License to You.</strong> Subject to your compliance with these Terms, you are granted a limited, non-sublicensable license to access and use the Services and content for your personal, non-commercial use. This license does not allow you to collect or use product listings, descriptions, or prices for the benefit of another merchant; use any data mining or similar data-gathering tools; or download (other than page caching) any portion of the Services, except with the express consent of Store1920. We reserve the right to terminate this license at any time for any reason.</p>

<p><strong>5.4 Feedback.</strong> We welcome and encourage feedback, comments, and suggestions for improvements to our Services (“Feedback”). If you choose to submit Feedback, you agree that we are free to use it without restriction or compensation to you. By accepting your submission, Store1920 does not waive any rights to use similar or related feedback previously known to Store1920, developed by its employees, or obtained from other sources.</p>

<p><strong>5.5 Third-Party Intellectual Property.</strong> We respect the intellectual property rights of others and ask our users to do the same. If you believe that any content on Store1920 infringes your intellectual property rights (for example, copyright or trademark), please notify us as outlined in our Intellectual Property Policy. We will investigate and take appropriate action, which may include removing or disabling access to the allegedly infringing material and/or terminating accounts of repeat infringers. Store1920’s Intellectual Property Policy explains how to report claims of infringement.</p>

<p><strong>5.6 User Content License to Others.</strong> If you post content (such as a review or photo) and make it publicly available to other users, you understand that such User Content can be viewed, saved, or shared by others. While these Terms do not grant other users any direct rights in your content, publicly posted content is no longer strictly private. Please consider this before posting personal or sensitive information. Store1920 is not responsible for how other users may use or misuse content you make public.</p>

<p><strong>5.7 DMCA (for Copyright Holders).</strong> If you are a copyright owner or an authorized agent and believe any content on our Services infringes your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) or similar laws by providing our Designated Copyright Agent with the required information. Please refer to our Intellectual Property Policy for contact details of the designated agent and further instructions on what to include in your notice. We will respond promptly to DMCA notices that comply with the law.</p>







      <h2>6. Termination</h2>
<p><strong>6.1 By You.</strong> You may stop using our Services at any time. You may also delete your Store1920 account at any time (via your account settings or by contacting us), but content you have posted (such as reviews) may still remain visible to others. Upon deletion of your account, these Terms will terminate, except that any provisions that by their nature should survive will continue to apply (see Section 13.3).</p>

<p><strong>6.2 By Store1920.</strong> We may suspend or terminate your account or your access to all or part of our Services at any time if: (a) you violate these Terms or any Policy; (b) we suspect fraudulent, abusive, or illegal activity; (c) we believe you create risk or possible legal exposure for us or other users; or (d) providing the Services to you is no longer commercially viable. We will make reasonable efforts to notify you via the email address associated with your account or the next time you attempt to access your account, depending on the circumstances. In most cases, we will give you a chance to resolve any issue with your account if practicable. However, in severe or repeated cases, termination may be immediate. If your account is terminated by us, you do not have a right to a restored account or any stored data, and we may refuse service to you in the future. Any balances or credits remaining on your account at termination may be forfeited, in accordance with applicable law.</p>

<p><strong>6.3 Effect of Termination.</strong> Upon termination of these Terms for any reason: (i) your license rights will end, and you must immediately cease all use of the Services; (ii) you will no longer be authorized to access your account or the Services; (iii) any outstanding obligations you owe to Store1920 will remain due (such as pending payments); and (iv) all provisions of these Terms intended to survive will continue in effect (including sections on limitation of liability, indemnification, dispute resolution, etc.). Store1920 will not be liable to you or any third party for compensation, reimbursement, or damages in connection with your use of the Services, or any termination or suspension of the Services or your account.</p>

<p><strong>6.4 Orders In-Progress.</strong> If your account is terminated while you still have pending orders (for example, items purchased but not yet delivered or returns in process), we will generally allow such transactions to conclude (by shipping the items or processing a return) as appropriate, or we may cancel them. If an order is canceled due to termination, you will receive a refund for any amounts paid for undelivered items.</p>









      <h2>7. Disclaimers and Limitations of Liability</h2>
<p><strong>7.1 No Warranty (Services Provided “As Is”).</strong> Store1920 provides the Services on an “AS IS” and “AS AVAILABLE” basis. To the maximum extent permitted by law, Store1920 (and its suppliers) makes no representations or warranties of any kind, express or implied, regarding the operation of the Services or the information, content, materials, products (including software), or other services made available through the Services. We disclaim all implied warranties, including implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. We do not guarantee that the Services will be uninterrupted, error-free, secure, or free of viruses or other harmful components. Your use of the Services is at your own risk. For example, we do not warrant that product descriptions or other content is accurate, complete, or current, and – aside from any remedies under our policies – we assume no liability for errors or omissions (e.g., pricing mistakes, typographical errors).</p>

<p><strong>7.2 Product Warranties Disclaimed.</strong> Any products made available via Store1920 are provided by third-party sellers “as is,” without warranties from Store1920 unless expressly stated otherwise. Any warranty on a product, if applicable, comes from the manufacturer or seller, not Store1920. Many new products may come with a manufacturer’s warranty; consult the product documentation or manufacturer’s website for warranty information and pursue remedies with them directly. Store1920’s role is primarily to facilitate the sale.</p>

<p><strong>7.3 Limitation of Liability.</strong> To the fullest extent permitted by law, Store1920 (including its officers, directors, employees, and agents) will not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from: (i) your use of or inability to use the Services; (ii) conduct or content of any third party on the Services, including defamatory, offensive, or illegal actions; (iii) content obtained from the Services; or (iv) unauthorized access, use, or alteration of your transmissions or content. Store1920’s aggregate liability for all claims relating to the Services will not exceed the greater of AED 500 or the total amount of payments you made to Store1920 during the 3 months preceding the claim. This limitation does not exclude liability for gross negligence, fraud, intentional misconduct, or other liability that cannot be limited by law. Some jurisdictions may not allow certain disclaimers or limitations; if so, you may have additional rights.</p>

<p><strong>7.4 Specific State/Country Law Rights.</strong> If you are a consumer residing in certain jurisdictions, you may have legal rights that prevent the above disclaimers or limitations from applying. These Terms are intended to comply with such laws and do not affect any non-waivable statutory rights.</p>

<p><strong>7.5 Third-Party Content.</strong> You may be exposed to content from various sources, including other users or third parties, when using the Services. Store1920 is not responsible for the accuracy, usefulness, safety, or intellectual property rights of such content. Use or reliance on this content is at your own risk. We are also not responsible for offensive, inappropriate, obscene, unlawful, or otherwise objectionable content you may encounter.</p>




      <h2>8. Indemnification</h2>
<p><strong>8. Indemnification.</strong> You agree to indemnify, defend, and hold harmless Store1920, its parent company, affiliates, and their respective officers, directors, employees, and agents (the “Indemnified Parties”) from and against any and all claims, liabilities, damages, losses, and expenses (including reasonable attorneys’ fees and costs) arising out of or in any way connected with: (a) your access to or use of the Services, including any actions taken by a third party using your account; (b) your User Content or feedback; (c) your breach or alleged breach of these Terms or any applicable law or regulation; (d) your violation of any rights of any third party, including intellectual property or privacy rights; or (e) any dispute you have with another user, seller, or buyer regarding a transaction.</p>

<p>Store1920 reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You may not settle any such claim without Store1920’s prior written consent. We will use reasonable efforts to notify you of any indemnifiable claim, action, or proceeding as soon as we become aware of it.</p>

<p>This indemnification obligation will survive the termination of these Terms and your use of the Services.</p>







      <h2>9. App Stores and Third-Party Platforms</h2>
<p><strong>9.1 Apple App Store.</strong> If you download our mobile application from Apple’s App Store, you acknowledge and agree to the following: (i) these Terms are between you and Store1920, not Apple, and Apple is not responsible for the app or its content; (ii) Apple has no obligation to provide any maintenance or support services for the app; (iii) if the app fails to conform to any warranty applicable to it, you may notify Apple, and Apple will refund any purchase price for the app (if any) to you – to the maximum extent permitted by applicable law, Apple will have no other warranty obligation with respect to the app, and any other claims, losses, liabilities, damages, costs, or expenses due to any failure of the app to conform to any warranty will be Store1920’s responsibility, not Apple’s; (iv) Apple is not responsible for addressing any claims by you or any third party relating to the app or your use of it, including product liability claims, claims that the app fails to comply with legal or regulatory requirements, and consumer protection claims; (v) Apple is not responsible for the investigation, defense, settlement, or resolution of any third-party claim that the app or your use of it infringes any third party’s intellectual property rights; and (vi) you agree to comply with any applicable third-party terms when using the app (e.g., your wireless data service terms). You and Store1920 agree that Apple and Apple’s subsidiaries are third-party beneficiaries of this Section and, upon your acceptance of these Terms, Apple has the right to enforce this Section against you as a third-party beneficiary.</p>

<p><strong>9.2 Google Play Store.</strong> If you download our mobile application from the Google Play Store, you acknowledge that Google is not responsible for providing support services for the app. In the event of any conflict between these Terms and the Google Play Developer Distribution Agreement as of the effective date of these Terms, the Google Play Developer Distribution Agreement will control.</p>

<p><strong>9.3 Other Platforms.</strong> If you access our Services via a third-party platform or social networking site (for example, logging in via Facebook or Google, or using a voice assistant integration), you understand that this agreement is between you and Store1920, not those third parties, and those third parties have no responsibility or liability for the Services. You must comply with all third-party terms of use when using the Services (for example, not violating Facebook’s terms when posting Store1920-related content on Facebook).</p>



      <h2>10. Promotions and Gift Cards</h2>
<p><strong>10.1 Promotions.</strong> Store1920 or its partners may offer contests, sweepstakes, giveaways, coupon codes, referral programs, or other promotions (collectively “Promotions”). Such Promotions may have additional terms and conditions, which will be provided to you at the time of the Promotion. By participating in any Promotion, you agree to comply with those additional terms as well as these Terms. If a Promotion’s rules conflict with these Terms, the Promotion rules will govern for that specific Promotion.</p>

<p><strong>10.2 Gift Cards.</strong> Store1920 may offer gift cards or credits for purchase or as part of Promotions. Gift cards are not redeemable for cash (except as required by law) and are non-transferable unless explicitly allowed by us. Lost or stolen gift cards cannot be replaced or refunded. Any additional terms accompanying Store1920 gift cards or credits will govern their use.</p>

<p><strong>10.3 Referral Credits.</strong> If you receive Store1920 credits through a referral program (for example, inviting a friend to join and shop), those credits may be subject to expiration and use limitations. Abuse of referral programs (such as self-referral or creating fake accounts) is prohibited and may result in loss of credits and termination of your account.</p>
      
 <h2>11. Miscellaneous</h2>
<p><strong>11.1 Governing Law.</strong> These Terms and any dispute between you and Store1920 shall be governed by the laws of the United Arab Emirates, without regard to its conflict of law principles. The United Nations Convention on Contracts for the International Sale of Goods (CISG) does not apply to these Terms.</p>

<p><strong>11.2 Exclusive Venue.</strong> Any dispute or claim not subject to arbitration (see Section 12) shall be exclusively decided by the courts of Dubai, United Arab Emirates. You and Store1920 each consent to the personal jurisdiction of these courts and waive any objection as to inconvenient forum (forum non conveniens).</p>

<p><strong>11.3 Online Dispute Resolution (EU Customers).</strong> This section is intentionally omitted, as Store1920 primarily serves UAE customers. If you are an EU customer, note that we are not currently participating in the EU’s ODR platform.</p>

<p><strong>11.4 Notice (How to Contact Each Other).</strong> You agree that Store1920 may provide notices to you by email to the address associated with your account, by postal mail, or by postings on our website or app. You are responsible for keeping your contact information up-to-date so that we can reach you. If we send email notice and you do not receive it because your information is incorrect or outdated, or you fail to check your email, our sending of the email will nonetheless constitute effective notice. You must send any notices to us either by: (a) email to <a href="mailto:legal@store1920.com">legal@store1920.com</a>, or (b) by certified mail or courier to: Althakeel General Trading LLC (Attn: Legal Department), Warsan, Dubai, United Arab Emirates. Notices sent by mail are considered received only when actually received at our mailing address.  
For questions or help regarding our Services, you may contact Customer Support via the “Contact Us” page on our website or the support section in the app.</p>

<p><strong>11.5 Waiver.</strong> If Store1920 does not enforce any provision of these Terms, it will not be considered a waiver of our rights. Any waiver of these Terms must be obtained in a written document signed by an authorized representative of Store1920 to be valid. Our failure to enforce any right or provision under these Terms in one instance will not constitute a waiver of that right or provision in any other instance.</p>
<p><strong>11.6 Severability.</strong> If any part of these Terms is found to be invalid, illegal, or unenforceable, that part shall be limited or eliminated to the minimum extent necessary, and the remainder of the Terms will remain in full force and effect. In other words, we want these Terms to be enforceable to the fullest extent allowed by law, and if a court strikes down any provision, the rest stays intact.</p>

<p><strong>11.7 Third-Party Beneficiaries.</strong> Except as expressly provided in Sections 9.1 (regarding Apple and Google) or elsewhere, there are no third-party beneficiaries to these Terms. That means no one other than you and Store1920 (and our successors and assigns) can enforce these Terms.</p>

<p><strong>11.8 Entire Agreement.</strong> These Terms (along with any applicable policies or additional terms we provide for specific services or features) constitute the entire agreement between you and Store1920 regarding your use of the Services, and supersede all prior and contemporaneous agreements, proposals, or representations, written or oral, concerning the same subject matter. If you and Store1920 have signed a separate written agreement governing your use of the Services, and that agreement conflicts with these Terms, the signed agreement will take precedence.</p>

<p><strong>11.9 Assignment.</strong> You may not assign or transfer these Terms (or any of your rights or obligations hereunder) without our prior written consent. Any attempt by you to assign without consent will be null. We may freely assign or transfer these Terms (in whole or in part) to an affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of our assets.</p>

<p><strong>11.10 No Agency.</strong> No joint venture, partnership, employment, or agency relationship exists between you and Store1920 as a result of these Terms or your use of the Services. You do not have any authority of any kind to bind Store1920 in any respect.</p>

<p><strong>11.11 Translation.</strong> Store1920 may provide translations of the English version of these Terms or other policies into other languages for your convenience. However, the English version is the authoritative version and shall control in case of any conflict or discrepancy. Versions in other languages are provided solely for convenience. If there are any inconsistencies between the English version of the Terms and a translated version, the English version will prevail.</p>


<h2>12. Arbitration Agreement and Dispute Resolution</h2>
<p><strong>12. Arbitration Agreement.</strong> Please read this Arbitration Agreement carefully. It is part of your contract with Store1920 and affects your rights. It contains procedures for MANDATORY BINDING ARBITRATION and a CLASS ACTION WAIVER.</p>

<p><strong>12.1 Applicability of Arbitration Agreement.</strong> You and Store1920 agree that any dispute, claim, or controversy arising out of or relating to these Terms or the use of the Services, will be resolved by binding arbitration, rather than in court, except for a few narrow exceptions listed below. This Arbitration Agreement is intended to be broadly interpreted. It includes, for example, disputes related to transactions on the Store1920 platform, Store1920’s advertisements or promotions, communications between you and Store1920, or the collection or use of personal data. It also includes disputes that may have arisen before you accepted these Terms (such as claims related to prior transactions) and after termination of use of the Services.</p>

<p><strong>Exceptions:</strong> Notwithstanding the above, either party may decide to take a dispute to small claims court (if it qualifies for that court’s jurisdictional limits as long as the matter remains in that court and on an individual basis). Also, either party may bring a lawsuit solely for injunctive relief to stop unauthorized use or abuse of the Services or infringement of intellectual property rights (for example, trademark, trade secret, copyright, or patent rights). Such actions are not subject to arbitration. Additionally, this Arbitration Agreement does not bar you from bringing issues to the attention of federal, state, or local agencies, which can seek relief on your behalf.</p>

<p><strong>12.2 Informal Dispute Resolution.</strong> Before initiating arbitration, you and we agree to first discuss the dispute informally for at least 30 days. If you have a dispute with Store1920, you should send a written notice to us at legal@store1920.com, briefly summarizing the dispute and your desired resolution. Include the email address associated with your account and any relevant order numbers. Store1920 will send any such notice to the email associated with your account (or other appropriate means). You and Store1920 will attempt to negotiate an informal resolution in good faith during the 30-day period. If the dispute is not resolved within that time, either party may proceed to initiate arbitration as set forth below. Engaging in this informal resolution is a requirement that must be fulfilled before commencing arbitration.</p>

<p><strong>12.3 Arbitration Procedures.</strong></p>

<p><strong>Initiating Arbitration:</strong> If we cannot resolve a dispute through informal negotiation, either party may start arbitration. To begin arbitration, the initiating party must provide the other a written Demand for Arbitration. (We will provide a copy of the AAA Demand for Arbitration form on request, or you can find it on AAA’s website.)</p>

<p><strong>Administrator:</strong> The arbitration will be administered by the American Arbitration Association (AAA) (or if AAA is unavailable, another reputable arbitration provider) under its Consumer Arbitration Rules in effect at the time the claim is filed. You can find AAA’s rules at www.adr.org or by calling 1-800-778-7879. Those rules are considered part of this Arbitration Agreement. If AAA is not available, the parties will agree on an alternative, or a court will appoint one.</p>

<p><strong>Arbitrator:</strong> The arbitration will be conducted by a single, neutral arbitrator. The arbitrator is bound by these Terms. The arbitrator has exclusive authority to resolve any dispute relating to interpretation, applicability, or enforceability of this Arbitration Agreement, including any claim that all or part of it is void or voidable, or whether a claim is subject to arbitration. However, a court will decide issues relating to the enforceability of the class action waiver in Section 12.5 below (i.e., Section 12.5 is not for an arbitrator to decide).</p>

<p><strong>Place and Process:</strong> Arbitration may be conducted in person, through the submission of documents, by phone, or online. If your claim is for AED 50,000 or less, we agree you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, or through a telephonic or in-person hearing as established by AAA rules. If your claim exceeds AED 50,000, the right to a hearing will be determined by AAA rules. Any in-person arbitration hearing will take place in Dubai, U.A.E., unless you and Store1920 both agree on an alternative location.</p>

<p><strong>12.4 Waiver of Jury Trial:</strong> You and Store1920 waive any constitutional and statutory rights to go to court and have a trial in front of a judge or a jury for all disputes subject to arbitration. Instead, you and Store1920 elect to have such disputes resolved by an arbitrator. Arbitration procedures are typically more limited, more efficient, and less costly than court, and are subject to very limited review by a court. In any litigation between you and Store1920 over whether to vacate or enforce an arbitration award, you and Store1920 waive all rights to a jury trial, and elect instead to have the dispute be resolved by a judge.</p>

<p><strong>12.5 Waiver of Class or Consolidated Actions:</strong> All claims and disputes within the scope of this Arbitration Agreement must be arbitrated on an individual basis and not on a class, representative, or collective basis. You and Store1920 agree not to bring any claim in arbitration as a class plaintiff, class member, or in a representative capacity on behalf of others. The arbitrator has no authority to: (a) combine or consolidate more than one person’s claims into a single case, or (b) preside over any kind of representative or class proceeding. The arbitrator can only decide individual claims for you and/or Store1920. This means that the arbitration award can only affect the parties to this arbitration, and cannot be used to affect other customers or users. If a court decides that applicable law precludes enforcement of any of this Section’s limitations as to a particular claim or request for relief (such as public injunctive relief), then that claim (and only that claim) must be severed from arbitration and may be brought in court, subject to your and our rights to appeal the court’s decision. All other claims will be arbitrated. This clause is an essential part of this Arbitration Agreement.</p>

<p><strong>12.6 Arbitration Fees and Incentives:</strong> Payment of all filing, administration, and arbitrator fees will be governed by the AAA’s rules. If your claim for damages does not exceed a certain amount (for example, $5,000 in the U.S., roughly AED 18,000) and is not frivolous, Store1920 will pay the filing fee on your behalf or reimburse it if you paid it. Additionally, we will not seek attorneys’ fees and costs in arbitration unless the arbitrator determines your claims are frivolous. Any request for payment of fees by Store1920 should be sent to AAA along with your Demand for Arbitration and Store1920 will make arrangements to pay administratively.</p>

<p><strong>12.7 Authority of Arbitrator:</strong> The arbitrator will decide the rights and liabilities, if any, of you and Store1920. The dispute will not be consolidated with any other matters or joined with any other cases or parties, except as provided in Section 12.5 above. The arbitrator has the authority to grant motions that dispose of all or part of any claim. The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to provide the relief warranted by that party’s individual claim, consistent with the Limitations of Liability section of these Terms. The arbitrator will provide a reasoned written statement of decision that is sufficient to explain the essential findings and conclusions on which the award is based. The arbitrator’s award is binding and may be entered as a judgment in any court of competent jurisdiction.</p>

<p><strong>12.8 Confidentiality:</strong> The arbitration proceedings and all information submitted therein shall be confidential, meaning neither you, Store1920, nor the arbitrator may disclose the existence, content, or results of any arbitration without the prior written consent of both parties, unless to protect or pursue a legal right, or as required by law.</p>

<p><strong>12.9 Opt-Out:</strong> You have the right to opt out of this Arbitration Agreement by sending us a written notice of your decision to opt out to legal@store1920.com or to our mailing address listed in Section 11.4, within 30 days of first accepting these Terms. Your notice must include your name, address, email (associated with your Store1920 account), and a clear statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of the Terms will continue to apply to you. Opting out will not affect any other arbitration agreements that you may have entered into with us in the past or future.</p>

<p><strong>12.10 Survival:</strong> This Arbitration Agreement will survive the termination of your relationship with Store1920.</p>

<p><strong>12.11 Severability (Arbitration):</strong> If any portion of this Arbitration Agreement is found to be unenforceable or unlawful for any reason, (1) the unenforceable provision shall be severed from these Terms; (2) severance of the provision shall have no impact whatsoever on the remainder of the Arbitration Agreement or the parties’ ability to compel arbitration of any remaining claims on an individual basis under this Arbitration Agreement; and (3) to the extent that any claims must therefore proceed on a class, collective, consolidated, or representative basis, those claims must be litigated in court (with jurisdiction as specified in Section 11.2) and not in arbitration, and the parties agree that litigation of those claims shall be stayed pending the outcome of any individual claims in arbitration. Furthermore, if any part of Section 12.5 (Class Action Waiver) is found to be unenforceable, then the entirety of this Arbitration Agreement shall be null and void, though the rest of the Terms will continue to apply.</p>

<p><strong>12.12 Future Changes to Arbitration Agreement:</strong> If we make any changes to this Arbitration Agreement (other than a change to the notice address), you may reject the change by sending us written notice within 30 days of the change to legal@store1920.com, in which case your account will be immediately terminated and this Arbitration Agreement, as in effect immediately prior to the changes you rejected, will survive.</p>

<p>________________________________________</p>

<p>Thank you for reading our Terms of Use. By shopping with Store1920, you agree to these Terms. If you have any questions or need clarifications, please contact us. Enjoy your experience on Store1920!</p>



   
    </div>
  );
};

export default TermsOfUse;
